### ISSUE TITLE
Turbinia's setup.py seems to be broken with the latest version of pip

### ISSUE THREAD

**Issue by tomchop** [google/turbinia#519]
Turbinia can't be isntalled with the latest version of `pip`. (20.1)

```
Collecting pip
  Downloading pip-20.1-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-20.1
[snip]
Collecting turbinia==20190819.6
  Downloading turbinia-20190819.6.tar.gz (88 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.6.10/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jz1lyg2d/turbinia/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jz1lyg2d/turbinia/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rm1k5ext
         cwd: /tmp/pip-install-jz1lyg2d/turbinia/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jz1lyg2d/turbinia/setup.py", line 65, in <module>
        'requirements.txt', session=False)
      File "/tmp/pip-install-jz1lyg2d/turbinia/setup.py", line 64, in <listcomp>
        install_requires=[str(req.req) for req in parse_requirements(
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
```

Works fine on pip 19.1.1.

**Comment by matejzero** [comment]
This might help: https://developercommunity.visualstudio.com/content/problem/1011562/azure-devops-python-build-pipeline-suddenly-stoppe.html

Or this: https://github.com/ansible/awx/pull/6880/files

**Comment by aarontp** [comment]
Thanks.  Yeah, I didn't realize this was actually broken (again) -- I knew I needed to eventually remove the pip internal `parse_dependencies()` call, and have https://github.com/google/turbinia/issues/492 for that, and previously removed the other pip internal reference, but I guess the other shoe has dropped for this :).

@alimez this might be a good fixit bug for you to look into if you want.  We basically need to either find some other way to parse the requirements.txt, or just inline the contents into setup.py.

**Comment by aarontp** [comment]
This has been fixed in HEAD, but I'm going to re-open this to track backporting this into the release branch and rolling out a new release.

**Comment by aarontp** [comment]
Patch release 20190819.7 has been pushed with this fix.
