### PR TITLE
Removed pip parse_requirments

### LINKED ISSUE #519: Turbinia's setup.py seems to be broken with the latest version of pip
Turbinia can't be isntalled with the latest version of `pip`. (20.1)

```
Collecting pip
  Downloading pip-20.1-py2.py3-none-any.whl (1.5 MB)
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 20.0.2
    Uninstalling pip-20.0.2:
      Successfully uninstalled pip-20.0.2
Successfully installed pip-20.1
[snip]
Collecting turbinia==20190819.6
  Downloading turbinia-20190819.6.tar.gz (88 kB)
    ERROR: Command errored out with exit status 1:
     command: /opt/hostedtoolcache/Python/3.6.10/x64/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-jz1lyg2d/turbinia/setup.py'"'"'; __file__='"'"'/tmp/pip-install-jz1lyg2d/turbinia/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-pip-egg-info-rm1k5ext
         cwd: /tmp/pip-install-jz1lyg2d/turbinia/
    Complete output (7 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-jz1lyg2d/turbinia/setup.py", line 65, in <module>
        'requirements.txt', session=False)
      File "/tmp/pip-install-jz1lyg2d/turbinia/setup.py", line 64, in <listcomp>
        install_requires=[str(req.req) for req in parse_requirements(
    AttributeError: 'ParsedRequirement' object has no attribute 'req'
```

Works fine on pip 19.1.1.

### PR DESCRIPTION
**Pull request by alimez**
fixes #519

### CODE REVIEW

**Comment by aarontp** [comment]
@alimez : LMK when you've tested this with pinned dependencies as discussed out of band.

**Comment by alimez** [comment]
@aarontp Tested requirements pinning in a separate virtualenv and downloaded all the requirements successfully. PTAL
